[flake8]
ignore = E501,W503
exclude =
    __pycache__/
    .obsidian/
    venv/
    .venv/
    .vscode/
    index/
    logs/
    test/
    tests/
    migrations/
    app/static/data/
    app.db
max-line-length = 99
